// File created at 09/29/2019 13:39
// 32 modules found

include(":animationresources")
include(":appupdateresources")
include(":authresources")
include(":barcoderesources")
include(":benchmarkresources")
include(":bluetoothprinterresources")
include(":bluetoothresources")
include(":bottomsheetresources")
include(":coreresources")
include(":corextresources")
include(":currencyinputresources")
include(":dataresources")
include(":dialogresources")
include(":domaindefinitionresources")
include(":drawableresources")
include(":drawerresources")
include(":fabmenuresources")
include(":facebookauthresources")
include(":firebasecoreresources")
include(":fluxarchresources")
include(":formresources")
include(":googlemapsresources")
include(":graphqlresources")
include(":imageloadingresources")
include(":locationresources")
include(":maskedittextresources")
include(":notificationresources")
include(":retrofitresources")
include(":schedulingresources")
include(":searchbarresources")
include(":spinnerresources")
include(":swiperevealresources")

setKotlinPluginsVersion()
