// File created at 10/24/2019 11:39
// 33 modules found

include(":animationresources")
include(":appupdateresources")
include(":authresources")
include(":barcoderesources")
include(":benchmarkresources")
include(":bluetoothprinterresources")
include(":bluetoothresources")
include(":bottomsheetresources")
include(":composeresources")
include(":coreresources")
include(":corextresources")
include(":currencyinputresources")
include(":dataresources")
include(":dialogresources")
include(":domaindefinitionresources")
include(":drawableresources")
include(":drawerresources")
include(":fabmenuresources")
include(":firebasecoreresources")
include(":fluxarchresources")
include(":formresources")
include(":googlemapsresources")
include(":graphqlresources")
include(":imageloadingresources")
include(":locationresources")
include(":maskedittextresources")
include(":notificationresources")
include(":okhttpresources")
include(":retrofitresources")
include(":schedulingresources")
include(":searchbarresources")
include(":spinnerresources")
include(":swiperevealresources")

setupKotlinSettings()
