name: build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9.x"

      - name: Setup Gradle
        run: |
          chmod +x gradlew
          export GRADLE_USER_HOME=$(pwd)/.gradle
          mv _build.gradle.kts build.gradle.kts
          mv _settings.gradle.kts settings.gradle.kts

      - name: Clone buildSrc
        run: git clone https://github.com/icarohs7/gradle-buildsrc buildSrc

      - name: Build
        run: python assembleDebug_each_ci.py

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}