name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install
        run: |
          sudo wget https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tgz
          sudo tar xzf Python-3.7.3.tgz
          cd Python-3.7.3
          sudo ./configure --enable-optimizations
          sudo make altinstall
          cd ..
          chmod +x gradlew
          export GRADLE_USER_HOME=$(pwd)/.gradle
          mv _build.gradle.kts build.gradle.kts
          mv _settings.gradle.kts settings.gradle.kts
          git clone https://github.com/icarohs7/unox-buildsrc buildSrc
      - name: Build
        run: |
          python3.7 assembleDebug_each_ci.py
      - name: Send coverage to codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}